# Generated by Django 3.2.4 on 2023-10-18 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idAlumnos', models.IntegerField(db_column='idAlumno', primary_key=True, serialize=False)),
                ('nameAlumno', models.CharField(db_column='nameAlumno', max_length=100)),
            ],
            options={
                'db_table': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.IntegerField(db_column='idGenero', primary_key=True, serialize=False)),
                ('tipoGenero', models.CharField(db_column='tipoGenero', max_length=100)),
            ],
            options={
                'db_table': 'Genero',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idRegistro', models.IntegerField(db_column='idRegistro', primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_column='usuario', max_length=100)),
                ('correo', models.EmailField(db_column='correo', max_length=254)),
                ('password', models.CharField(db_column='password', max_length=100)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Alumno_has_Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Alumno', models.ForeignKey(db_column='fk_Alumno', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.alumno')),
                ('fk_Genero', models.ForeignKey(db_column='fk_Genero', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
            ],
            options={
                'db_table': 'alumno_has_genero',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='fk_genero',
            field=models.ForeignKey(db_column='fk_genero', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.genero'),
        ),
    ]
